from typing import Protocol, List
from MemAgent.model.record import MemRecord, ToolRecord, Persona

class MemoryProvider(Protocol):
    async def upsert(self, rec: MemRecord) -> None: ...
    async def search(self, query: str, mem_types: list[str], k: int = 8) -> List[MemRecord]: ...
    async def stream_conversation(self, conv_id: str): ...
    async def log_workflow_step(self, workflow_id: str, step: dict): ...
    async def entity_facts(self, entity_id: str, k: int = 10): ...
    async def match_tools(self, msg: str, k: int = 4) -> List[ToolRecord]: ...
    async def persona(self, persona_id: str) -> Persona: ...
